declare namespace NodeJS {
  export interface ProcessEnv {
    NEXT_PUBLIC_WEBAPP_URL?: string;
    NEXT_PUBLIC_MARKETING_URL?: string;
    NEXT_PRIVATE_INTERNAL_WEBAPP_URL?: string;

    NEXT_PRIVATE_DATABASE_URL: string;

    NEXT_PUBLIC_STRIPE_COMMUNITY_PLAN_MONTHLY_PRICE_ID: string;

    NEXT_PRIVATE_STRIPE_API_KEY: string;
    NEXT_PRIVATE_STRIPE_WEBHOOK_SECRET: string;

    NEXT_PRIVATE_GOOGLE_CLIENT_ID: string;
    NEXT_PRIVATE_GOOGLE_CLIENT_SECRET: string;

    NEXT_PRIVATE_OIDC_WELL_KNOWN: string;
    NEXT_PRIVATE_OIDC_CLIENT_ID: string;
    NEXT_PRIVATE_OIDC_CLIENT_SECRET: string;
    NEXT_PRIVATE_OIDC_ALLOW_SIGNUP?: string;
    NEXT_PRIVATE_OIDC_SKIP_VERIFY?: string;

    NEXT_PRIVATE_LARAVEL_API_URL?: string;
    NEXT_PRIVATE_LARAVEL_ENCRYPTION_KEY?: string;

    AZURE_STORAGE_ACCOUNT_NAME: string;
    AZURE_STORAGE_ACCOUNT_KEY: string;
    AZURE_STORAGE_CONNECTION_STRING: string;
    AZURE_STORAGE_CONTAINER_NAME: string;
    AZURE_STORAGE_URL: string;
    FOLDER_FILE: string;
    NEXT_PUBLIC_CD_SERVICE_URL?: string;
  }
}
