services:
  documenso-next:
    build: .
    ports:
      - '3002:3002'
    env_file:
      - .env
    restart: always

  nginx_documento_next:
    image: nginx:alpine
    container_name: nginx_documento_next
    ports:
      - '9000:80'
      - '4443:4443'
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - documenso-next
