services:
  documenso-next:
    build: .
    ports:
      - '3002:3002'
    environment:
      - NODE_ENV=production
      - PORT=3002
      - NEXTAUTH_URL=${NEXTAUTH_URL:-${NEXT_PUBLIC_WEBAPP_URL}}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET:?err}
      - NEXT_PRIVATE_ENCRYPTION_KEY=${NEXT_PRIVATE_ENCRYPTION_KEY:?err}
      - NEXT_PRIVATE_ENCRYPTION_SECONDARY_KEY=${NEXT_PRIVATE_ENCRYPTION_SECONDARY_KEY:?err}
    volumes:
      - .:/app
      - /app/node_modules
    restart: always

  nginx_documento_next:
    image: nginx:alpine
    container_name: nginx_next
    ports:
      - '9000:80'
      - '4443:4443'
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - documenso-next
